--- 
title: "Data Science Campus Project Standards"
author: "Nathan Eastwood"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
github-repo: datasciencecampus/workflow
output:
  bookdown::gitbook:
    config:
      sharing: no
    css: custom.css
documentclass: book
---

# Preface {-}

The purpose of this document is to define correct coding standards and project best practices to be used within the Data Science Campus (DSC) at the Office for National Statistics (ONS).

```{r knitrPrefs, include = FALSE}
knitr::opts_chunk$set(
  fig.height = 6,
  fig.align = "center"
)
```


# Dependency Management {#deps}

Dependency management systems are incredibly important, particularly in the world of analysis. Whenever we produce some code to perform statistical analysis or machine learning, we need to be able to recreate those results exactly. This could be the day after or the year after and we need to know which versions of which packages we must have installed on our machine. Updates to packages can produce breaking changes and our code may produce slightly different results, or worse yet, not run at all. Then installing a specific packages for a certain project may make code on other projects break.

<blockquote class="twitter-tweet tw-align-center" data-lang="en-gb"><p lang="en" dir="ltr">That results can change so much with different pkg versions is scary (and ignored by many) <a href="https://t.co/wn5x3UBgQz">https://t.co/wn5x3UBgQz</a> <a href="https://twitter.com/hashtag/rstats?src=hash">#rstats</a> <a href="https://twitter.com/hashtag/reproducibility?src=hash">#reproducibility</a> <a href="https://t.co/Jp4ASOKC81">pic.twitter.com/Jp4ASOKC81</a></p>&mdash; F Rodriguez-Sanchez (@frod_san) <a href="https://twitter.com/frod_san/status/847085478469947392">29 March 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Moreover, you may be presented with someone else's code but without them explicitly stating which packages you need, it is not always obvious, and even then you still have the manual challenge of installing the correct versions of each package yourself. These packages may then end up being globally installed when you don't need them for any other project, therefore clogging up your system.
